import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import ClientProvider from "@/ClientProvider";
import Navbar from "@/components/ui/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html
    lang="en"
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
  >
    {/* Removed 'dark' class if you are transitioning to the light earthy theme, but kept flex */}
    <body className="min-h-full flex bg-[#F3EBDD]">
      <ClientProvider>
        <Navbar />
        
        {/* Wrap children here to add bottom padding on mobile (pb-20) and remove it on desktop (md:pb-0) */}
        <main className="flex-1 w-full pb-20 md:pb-0">
          {children}
        </main>
        
        <Toaster />
      </ClientProvider>
    </body>
  </html>
);
}
